Category controller
an-kiian/GD-Training-Project pull request #17
Opened 2020-07-23 10:43 UTC by pVlasenko

-add category from properties
-add category controller test

2020-07-23 10:56 UTC, an-kiian commented on src/test/java/store/controller/CategoryControllerTest.java
> +
I think it's not  correct to create @Mock and @InjectMocks. Only @InjectMocks is needed

2020-07-23 10:58 UTC, an-kiian commented on src/test/java/store/controller/CategoryControllerTest.java
> +        List<String> resultList = categoryController.getAll();
it's not necessary to make "when" for one object(contoller) and then use another object(categoryController) to check method.

2020-07-24 10:34 UTC, MaxAbrosimov requested changes

2020-07-24 10:34 UTC, MaxAbrosimov commented on src/main/java/store/controller/CategoryController.java
> +    List<String> categories;
Test doesnt have an access to spring props.
Search in google how to set value to private field

2020-07-27 10:09 UTC, MaxAbrosimov approved these changes

2020-07-27 10:15 UTC, merged